// <auto-generated />
using System;
using EFCORE.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCORE.DATA.Migrations
{
    [DbContext(typeof(FootballLeagueDBContext))]
    partial class FootballLeagueDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("EFCORE.DOMAIN.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("coaches");
                });

            modelBuilder.Entity("EFCORE.DOMAIN.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arafat",
                            createdDate = new DateTime(2024, 1, 25, 15, 3, 50, 392, DateTimeKind.Unspecified).AddTicks(770)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hossain",
                            createdDate = new DateTime(2024, 1, 25, 15, 3, 50, 392, DateTimeKind.Unspecified).AddTicks(840)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
